### ISSUE TITLE
resilience to "bad json" errors

### ISSUE THREAD

**Issue by sidetrackedmind** [codeforpdx/opentransit-collector#6]
## Problem
Trimet's API response can have "bad json" (i.e. json-like string that breaks a parser). This will break the line https://github.com/codeforpdx/opentransit-collector/blob/831edff06fbb041d5018d427ff57e5baa2646fe8/src/providers/gtfs-trimet.js#L20

## Goals

- Primary - Make sure that the collector-dev docker stays alive when it encounters "bad json". 
- Nice to have - Capture timestamp and bad json string if possible for future reporting to Trimet?

**Comment by liamphmurphy** [comment]
This is being worked on in #7.
